---
title: "Robert E. Settlage"
description: |
  Welcome!!  WIP, for sure, have requests? Submit as an issue ...
site: distill::distill_website
listing: posts
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE) 

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```


 
## Me in a nutshell

I am a chemist, statistician, and compute junkie all rolled up into one.  I am the bioinformatician doing the COVID surveillance sequencing analysis for SW-VA.  I am the NVidia Deep Learing Institute Ambassador to Virginia Tech.  I love data, bigger is better.  Something big enough to challenge the available compute.  I love automation.  Do it the first time, it is research, do it a second time, it is productionizing (bug fixing ;) ), a third time is now monotonous and should be automated.

People have asked me "What is big data?"  To me, big data does what I just stated, challenges the available compute.  I would prefer that to mean some large cluster or cloud resource, but the truth is that all of us use our local platform at some point, so it is a frame of reference.

My favorite things include seeing the "AHA" moment in students/researchers/faculty when I enable them in some way.  That some way could mean showing them how to use our clusters at VT, it could mean helping code up some sort of script to analysize their data.  It could also be sharing with them the project I am involved in, Open OnDemand, which is an enabler for new or non-traditional high performance computing (HPC) users.  It doesn't really matter what the trigger is, the AHA moment is always special.

On this site, you will see my collection of learnings.  I am writing this for me, but hope you will get something from them.  What am I hoping to get from this is both clarity as I write and explain for me and a record of my journey.  I may also include some of my automation projects.  What do I mean by automation, here is a snapshot of my GitHub personal view:

## TODO
+ add GitHub calendar
+ tighten up above and add some bullets of fun/etc



